name: linux

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:
    branches: [ '*' ]

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
        - '5.20'
        - '5.22'
        - '5.24'
        - '5.26'
        - '5.28'
        - '5.30'
        include:
          - perl-version: '5.32'
            os: ubuntu-latest
            coverage: true
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
    - uses: actions/checkout@v2
    - run: env | sort
    - run: perl -V
    - run: cpanm -n --installdeps .
    - name: Run tests (no coverage)
      if: ${{ !matrix.coverage }}
      run: prove -lr t
    - name: Run tests (with coverage)
      if: ${{ matrix.coverage }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cpanm -n Devel::Cover::Report::Coveralls
        perl Build.PL && ./Build build && cover -test -report coveralls
